### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Google_Service_Analytics' not found

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodir-google-analytics#16]
https://secure.helpscout.net/conversation/1438868573/15554?folderId=3812058
https://secure.helpscout.net/conversation/1263215456/7099
https://secure.helpscout.net/conversation/1227711843/5434
https://secure.helpscout.net/conversation/1193976215/3883
https://secure.helpscout.net/conversation/1190295738/3685

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodir-google-analytics/commit/20cad91a584176af759fda3a2be6a918d072ee3b
