### ISSUE TITLE
Extend to more than details page

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodir-google-analytics#5]
1. make work on BP author pages
2. make work on post/pages.
3. pretty much everywhere else

**Comment by Stiofan** [comment]
https://wpgeodirectory.com/support/topic/google-analytics-v2-beta-extension-to-buddpress-member-homepage/

**Comment by picocodes** [comment]
on it

**Comment by Stiofan** [comment]
Please make sure this works on BuddyPress and UWP author pages for (owner)
